### ISSUE TITLE
[BUG]: Google Account not Found.

### ISSUE THREAD

**Issue by manuelduarte077** [stevdza-san/DiaryApp#2]
After finishing the course lessons, I came across this error, I couldn't find how to solve it

<img src="https://github.com/stevdza-san/DiaryApp/assets/46093689/f7bdf031-6198-40e5-9f36-8c987ddb09fd" width="250" />

**Comment by stevdza-san** [comment]
That error is connected with One-Tap Sign in with Google API. I've updated my One-Tap Compose library (1.0.5) to provide you with some additional logging information. One of the reasons why you may be getting that error, is because an android emulator has some issues with that API. Sometimes even though you have already connected your Gmail account with the emulator, you still may experience that issue. My suggestion is to test it out on a real device. Also once again, update OneTapCompose to the newest version in order to see some extra logging info.

**Comment by manuelduarte077** [comment]
After I update the library, it throws me this error
`Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.stevdza-san:OneTapCompose:1.0.5.`


<img width="1303" alt="Screenshot 2023-06-14 at 20 22 28" src="https://github.com/stevdza-san/DiaryApp/assets/46093689/a4161b6e-c0ea-4ef2-b894-4ece0c30d8dd">

**Comment by stevdza-san** [comment]
The latest version is: 1.0.3
